/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifmt.maromba2a;

/**
 *
 * @author geekaia
 */
public class CALCULOS extends javax.swing.JFrame {

    public void acaoManter() { 
        btnManter.setSelected(true);
        btnEngordar.setSelected(false);
        btnEmagrecer.setSelected(false);
    }
    public void acaoEngordar() { 
        btnManter.setSelected(false);
        btnEngordar.setSelected(true);
        btnEmagrecer.setSelected(false);
    }
    public void acaoEmagrecer() { 
        btnManter.setSelected(false);
        btnEngordar.setSelected(false);
        btnEmagrecer.setSelected(true);
    }
    public void acaoMasculino() { 
        btnMasculino.setSelected(true);
        btnFeminino.setSelected(false);
    }
    
    public void acaoFeminino() { 
        btnMasculino.setSelected(false);
        btnFeminino.setSelected(true);
    }
    /**
     * Creates new form CALCULOS
     */
    public CALCULOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbResultado = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        btnCalcularIMC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPesoCalorias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnManter = new javax.swing.JToggleButton();
        btnEngordar = new javax.swing.JToggleButton();
        btnEmagrecer = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        btnMasculino = new javax.swing.JToggleButton();
        btnFeminino = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JSpinner();
        btnCalcular = new javax.swing.JButton();
        lbCalRes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Peso");

        jLabel2.setText("Altura");

        lbResultado.setText("Resultado");

        btnCalcularIMC.setText("Calcular IMC");
        btnCalcularIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularIMCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lbResultado)
                    .addComponent(txtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addComponent(txtAltura))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCalcularIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 443, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lbResultado)
                .addGap(18, 18, 18)
                .addComponent(btnCalcularIMC)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("IMC", jPanel1);

        jLabel3.setText("Peso");

        jLabel4.setText("Objetivo");

        btnManter.setText("Manter");
        btnManter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManterActionPerformed(evt);
            }
        });

        btnEngordar.setText("Engordar");
        btnEngordar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngordarActionPerformed(evt);
            }
        });

        btnEmagrecer.setText("Emagrecer");
        btnEmagrecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmagrecerActionPerformed(evt);
            }
        });

        jLabel5.setText("Sexo");

        btnMasculino.setText("Masculino");
        btnMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasculinoActionPerformed(evt);
            }
        });

        btnFeminino.setText("Feminino");
        btnFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFemininoActionPerformed(evt);
            }
        });

        jLabel6.setText("Idade");

        btnCalcular.setText("Calcular Calorias");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lbCalRes.setText("Calorias:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(txtPesoCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnManter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEngordar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmagrecer))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnMasculino)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnFeminino)))
                    .addComponent(lbCalRes, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesoCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManter)
                    .addComponent(btnEngordar)
                    .addComponent(btnEmagrecer))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMasculino)
                    .addComponent(btnFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(lbCalRes)
                .addGap(18, 18, 18)
                .addComponent(btnCalcular)
                .addContainerGap())
        );

        jTabbedPane1.addTab("CALORIAS", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIMCActionPerformed
        // TODO add your handling code here:
        String peso = txtPeso.getText();
        String altura = txtAltura.getText();
        try{ 
            Double pesod = Double.parseDouble(peso);
            Double alturad = Double.parseDouble(altura);
            Double imc = pesod / (alturad*alturad); 
            String res="";
            if (imc < 18.5) {
                res="MAGREZA";
            }else  if (imc <= 24.9){
                res="NORMAL";
            } else  if (imc <= 29.9){
                res="SOBREPESO";
            } else  if (imc <= 39.9){
                res="OBESIDADE";
            } else   {
                res="OBESIDADE GRAVE";
            }
              
            lbResultado.setText("Resultado: "+res+" IMC: "+ imc);
        }catch(Exception e) {
            e.printStackTrace();
            lbResultado.setText("Resultado: erro no cálculo");
        }
    }//GEN-LAST:event_btnCalcularIMCActionPerformed

    private void btnManterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManterActionPerformed
        // TODO add your handling code here:
        acaoManter(); 
    }//GEN-LAST:event_btnManterActionPerformed

    private void btnEngordarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngordarActionPerformed
        // TODO add your handling code here:
        acaoEngordar();
    }//GEN-LAST:event_btnEngordarActionPerformed

    private void btnEmagrecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmagrecerActionPerformed
        // TODO add your handling code here:
        acaoEmagrecer();
    }//GEN-LAST:event_btnEmagrecerActionPerformed

    private void btnMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasculinoActionPerformed
        // TODO add your handling code here:
        acaoMasculino();
    }//GEN-LAST:event_btnMasculinoActionPerformed

    private void btnFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFemininoActionPerformed
        // TODO add your handling code here:
        acaoFeminino();
    }//GEN-LAST:event_btnFemininoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
 
        
        String peso = txtPesoCalorias.getText(); 
        String idade = txtIdade.getValue().toString(); 
        
        String sexo="nulo"; 
        if (btnMasculino.isSelected()) {
            sexo="M"; 
        } else if(btnFeminino.isSelected()) {
            sexo="F"; 
        }
        Double pesod = Double.parseDouble(peso);
        Integer idadei = Integer.parseInt(idade);
        double caloriasBasal=0;
        if (sexo.equals("F")) {
            if (idadei <= 3) {
                caloriasBasal = (58.317 * pesod) - 31.1;
            }  else if (idadei <= 10) {
                caloriasBasal = (20.315 * pesod) + 485.9;
            } 
        } else {
            if (idadei <= 3) { //(59,512 x peso em kg) – 30,4
                caloriasBasal = (59.512 * pesod) - 30.4;
            } else if (idadei <= 10) { //(59,512 x peso em kg) – 30,4
                caloriasBasal = (22.706 * pesod) + 504.3;
            }  // (22,706 
        }
        lbCalRes.setText("Gasto calórico: "+ caloriasBasal);
        
        


            
         
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CALCULOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CALCULOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CALCULOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CALCULOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CALCULOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcularIMC;
    private javax.swing.JToggleButton btnEmagrecer;
    private javax.swing.JToggleButton btnEngordar;
    private javax.swing.JToggleButton btnFeminino;
    private javax.swing.JToggleButton btnManter;
    private javax.swing.JToggleButton btnMasculino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCalRes;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JSpinner txtIdade;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPesoCalorias;
    // End of variables declaration//GEN-END:variables
}
